Build: Fix compile time warnings
BlueAndi/ZumoHALWebots pull request #5
Opened 2024-06-11 15:14 UTC by nhjschulz

Compiling with -Wall -Wextra results in the following warnings:

    .pio\libdeps\Example\ZumoHALWebots\src/Keyboard.h: In constructor
    'Keyboard::Keyboard(SimTime&, webots::Keyboard*)':
    .pio\libdeps\Example\ZumoHALWebots\src/Keyboard.h:247:14: warning:
    'Keyboard::m_simTime' will be initialized after [-Wreorder]
      247 |     SimTime& m_simTime; /**< Simulation time */

    .pio\libdeps\Example\ZumoHALWebots\src\Settings.cpp: In member function
    'bool Settings::loadSettings()':
    .pio\libdeps\Example\ZumoHALWebots\src\Settings.cpp:108:22: warning:
    comparison of integer expressions of different signedness: 'long int'
    and 'size_t' {aka 'long long unsigned int'} [-Wsign-compare]
      108 |         if (fileSize == fread(buffer, sizeof(char), fileSize,
          fd))

2024-06-11 15:28 UTC, BlueAndi requested changes

2024-06-11 15:28 UTC, BlueAndi commented on src/Settings.cpp
> +    return (size_t)(end - begin);
Please use C++ casts, no C-casts.

2024-06-12 07:58 UTC, nhjschulz commented on src/Settings.cpp
> +    return (size_t)(end - begin);
now static_cast<> used

2024-06-12 09:14 UTC, BlueAndi approved these changes

2024-06-12 09:18 UTC, merged